### ISSUE TITLE
Typo in vars

### ISSUE THREAD

**Issue by alex0ptr** [telekomsecurity/TelekomSecurity.Compliance.Automation#7]
There is a typo `tru` instead of `true`:

https://github.com/telekomsecurity/TelekomSecurity.Compliance.Automation/blob/master/T-Sec.SSH.Compliance/vars/vars_ssh(01)ssh-requirements.yml#L79

**Comment by rascherm** [comment]
Danke für den Hinweis,

bitte auch mal hier reinschauen :
https://github.com/telekom/tel-it-security-automation

Viele Grüße
Mirko Rascher

Kommende geplante Abwensenheit: Mo 23.3. – Fr 27.3.

Von: Alex Krause <notifications@github.com>
Gesendet: Dienstag, 11. Februar 2020 13:13
An: telekomsecurity/TelekomSecurity.Compliance.Automation <TelekomSecurity.Compliance.Automation@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [telekomsecurity/TelekomSecurity.Compliance.Automation] Typo in vars (#7)


There is a typo tru instead of true:

https://github.com/telekomsecurity/TelekomSecurity.Compliance.Automation/blob/master/T-Sec.SSH.Compliance/vars/vars_ssh(01)ssh-requirements.yml#L79
